import type { AbilityId } from '../core/types';

export interface AbilityPresentation {
  name: string;
  description: string;
  destinationSubject?: 'actor' | 'target';
}

const ability = (
  name: string, description: string,
  destinationSubject?: AbilityPresentation['destinationSubject'],
): AbilityPresentation => ({
  name, description, ...(destinationSubject ? { destinationSubject } : {}),
});

/** Presentation-only explanations for every rules-facing ability tag. */
export const ABILITY_PRESENTATION: Record<AbilityId, AbilityPresentation> = {
  ranged: ability('Ranged', 'Can shoot while shots remain. Adjacent enemies and very distant targets reduce ranged damage.'),
  flying: ability('Flying', 'Ignores battlefield movement blockers.'),
  beast: ability('Beast', 'Counts as a Beast for skills, artifacts, and other effects.'),
  construct: ability('Construct', 'Counts as a Construct for repair and other effects.'),
  spirit: ability('Spirit', 'Counts as a Spirit for spells and other effects.'),
  banner: ability('Banner', 'Adjacent allies gain morale at the start of each round.'),
  charge: ability('Charge', 'Deals 5% more attack damage per hex moved before striking, up to +50%.'),
  oriflamme: ability('Oriflamme', 'All allies gain morale each round and are steadied when an allied company is destroyed.'),
  rampant: ability('Rampant', 'Gains morale whenever an ally receives a morale-triggered extra action.'),
  springloaded: ability('Spring-Loaded', 'Its first attack each battle deals 50% more damage.'),
  no_retaliation: ability('No Retaliation', 'Enemies cannot retaliate against its attacks.'),
  soft_body: ability('Soft Body', 'Incoming attacks use the minimum of the attacker’s damage range.'),
  overwind: ability('Overwind', 'Take an extra full action now, then skip this company’s entire next round.'),
  procession_of_repair: ability('Procession of Repair', 'Spend the action to restore 15% maximum HP to every adjacent allied company, reviving units.'),
  hallowed_cargo: ability('Hallowed Cargo', 'If this company survives a victory, the army recovers additional Wound-Wrights spare parts.'),
  last_light: ability('Last Light', 'When destroyed, applies Hex to every adjacent enemy.'),
  the_errand_passes: ability('The Errand Passes', 'When destroyed, grants an allied company an immediate free move without an attack.'),
  still_on_watch: ability('Still on Watch', 'May retaliate any number of times each round.'),
  swelling_dirge: ability('Swelling Dirge', 'Deals 5% more damage for every company destroyed during this battle.'),
  unfinished_vow: ability('Unfinished Vow', 'The first time it is destroyed each battle, it returns with half its pre-battle company.'),
  crossing: ability('Crossing', 'Spend the action to carry an adjacent allied company to a free battlefield hex.', 'target'),
  sting_and_circle: ability('Sting and Circle', 'Returns to the hex it attacked from after striking.'),
  web: ability('Web', 'Ranged attacks also apply Chill 2.'),
  resin_trail: ability('Resin Trail', 'Hexes crossed become resin; enemies starting a turn there gain Chill.'),
  skim: ability('Skim', 'May strike two adjacent enemy companies in one attacking pass.'),
  brood_call: ability('Brood Call', 'Once per battle, spend the action to summon Larvae based on casualties so far.'),
  pecking_order: ability('Pecking Order', 'Attacks apply Hex 1.'),
  boundary: ability('Boundary', 'Enemies beginning their turn adjacent have their speed halved for that turn.'),
  sweep: ability('Sweep', 'Pushes the target one hex after attacking.'),
  beckoning_song: ability('Beckoning Song', 'Once per battle, forces an enemy to move toward this company.'),
  home_ground: ability('Home Ground', 'Creates two allied thicket hexes when battle begins.'),
  thicket_walk: ability('Thicket Walk', 'May enter and stand on obstacles and thickets.'),
  fowl_legs: ability('Fowl Legs', 'May relocate to a free hex at the end of a round.'),
  crone_favor: ability('Crone’s Favor', 'While it lives, its hero’s Wild and Grave spells cost one less mana.'),
  skirmish: ability('Skirmish', 'May use remaining speed to move after attacking.'),
  war_drums: ability('War Drums', 'Allies that lost units since their last turn gain morale at round start.'),
  pack_hunger: ability('Pack Hunger', 'Deals 15% more damage to companies that have already lost units this battle.'),
  trample: ability('Trample', 'May move through enemies, damaging them as it passes.', 'actor'),
  undergrass: ability('Undergrass', 'Ignores movement blockers and cannot be retaliated against.'),
  storm_wake: ability('Storm Wake', 'After attacking, applies Burn to enemies adjacent to the target.'),
  siege_wall: ability('Wall Section', 'An immobile siege obstacle that blocks movement and protects the defending side.'),
  siege_ram: ability('Siege Ram', 'A broad construct that deals double damage to city walls.'),
  immobile: ability('Immobile', 'Cannot move from its battlefield position.'),
  mirror_hex: ability('Mirror Hex', 'An immobile mirror created as a battlefield obstacle.'),
  aquatic: ability('Aquatic', 'Ignores shallow-water movement cost and gains speed while standing in shallows.'),
  the_song: ability('The Song', 'Ranged attacks also drain 10 morale from the target.'),
  still_aboard: ability('Still Aboard', 'When destroyed, deals part of its former total HP to its killer.'),
  shellback: ability('Shellback', 'Ranged attacks against it use the minimum of the attacker’s damage range.'),
  the_lure: ability('The Lure', 'Once per battle, forces an enemy to move toward this company.'),
  full_heal: ability('Whole by Morning', 'Heals back to its battle-start strength at the end of every round.'),
  melee_reflect: ability('Blades Return', 'Melee damage is reflected completely to the attacker instead.'),
  mask_reflect: ability('Mirror Mask', 'Enemy melee attackers suffer part of the damage they deal.'),
  hex_feeder: ability('Hex Feeder', 'Deals 10% more damage for every Hex on its target, in addition to Hex’s normal effect.'),
  counter_eater: ability('Counter-Eater', 'At turn start, consumes one of every counter it carries and gains +1 Attack per counter until its next turn.'),
  burn_conduit: ability('Burn Conduit', 'Its attacks move 2 Burn from itself to the target; if it has no Burn, they apply Burn 1.'),
  bloomshare: ability('Bloomshare', 'When Bloom heals this company, adjacent allies heal for half that amount without resurrection.'),
  echoing: ability('Echoing', 'Spells its hero casts targeting this company gain +1 counter magnitude and +1 round of duration.'),
  spell_battery: ability('Spell Battery', 'While this company lives, its hero’s spells cost 1 less mana, minimum 1.'),
  mana_leech: ability('Mana Leech', 'The first time each round it damages an enemy, transfers 1 mana from the enemy hero to its hero.'),
  spell_shrug: ability('Spell Shrug', 'Takes half damage from impact spells.'),
  spellbound: ability('Spellbound', 'Cannot be targeted by any spell, friendly or hostile.'),
  sniper: ability('Sniper', 'Ignores the ranged penalty for targets more than seven hexes away.'),
  chain_shot: ability('Chain Shot', 'A shot also hits the first adjacent non-primary company for half damage; the secondary may be friendly.'),
  first_strike: ability('First Strike', 'When attacked in melee, retaliates before damage; destroying the attacker cancels its attack.'),
  phalanx: ability('Phalanx', 'Adjacent allied companies take 15% less damage; multiple Phalanxes do not stack.'),
  unstable: ability('Unstable', 'On destruction, deals 20% of its starting maximum HP to every adjacent company on both sides.'),
  soul_tithe: ability('Soul Tithe', 'Whenever an enemy company is destroyed, gains +1 Attack for the rest of the battle.'),
  blink_step: ability('Blink Step', 'Once per battle, spend the action to move to any legal empty hex.', 'actor'),
  altar: ability('Altar', 'Destroy an adjacent friendly summoned company; fully heal this company and grant its hero 2 mana.', 'target'),
  hedge_caster: ability('Hedge Caster', 'Once per battle, spend the company action to cast its fixed tier-1 spell at printed power without using the hero act.', 'target'),
  ward_bearer: ability('Ward Bearer', 'Once per battle, the first enemy single-target spell aimed at an adjacent ally retargets here.'),
  siphon: ability('Siphon', 'Half the damage it deals heals the allied company with the lowest current HP.'),
  caster: ability('Caster', 'Spend the company action and one per-company charge to cast a printed repertoire spell at fixed power; this does not use the hero act.', 'target'),
  warded_hide: ability('Warded Hide', 'Reduces spell damage by the printed 25%, 40%, or 60%.'),
  low_magic_immune: ability('Low Magic Immune', 'Tier 1–2 spells have no effect; higher-tier spells still work.'),
  school_resistant: ability('School Resistant', 'Single-target spells of the printed school have no effect; mass and enchantment effects still work.'),
  unburnable: ability('Unburnable', 'Cannot gain Burn; any Burn already present is removed.'),
  unchillable: ability('Unchillable', 'Cannot gain Chill; any Chill already present is removed.'),
  unhexable: ability('Unhexable', 'Cannot gain Hex; any Hex already present is removed.'),
  spell_ward: ability('Spell Ward', 'The first printed number of spells targeting this company each battle have no effect.'),
  spell_deflect: ability('Spell Deflect', 'The first enemy spell targeting this company is redirected to a legal company on the caster’s side.'),
  spell_frail: ability('Spell Frail', 'Takes 50% more spell damage and receives +1 counter whenever a spell applies one.'),
  all_adjacent: ability('All Adjacent', 'A melee attack strikes every enemy adjacent to this company at full damage; none retaliate.'),
  breath: ability('Breath', 'A melee attack also deals full damage to the company directly beyond the target, including an ally; only the primary may retaliate.'),
  cleave: ability('Cleave', 'A melee attack deals half damage to companies flanking the target, including allies; only the primary may retaliate.'),
  line_strike: ability('Line Strike', 'Strikes every company in the printed straight-line range for 100%, 75%, then 50% damage; friendly fire, no retaliation.'),
  blast_shot: ability('Blast Shot', 'One shot hits the primary at full damage and every adjacent company at half damage, including allies; no retaliation.'),
  arc_shot: ability('Arc Shot', 'One shot jumps to the nearest enemies, up to three total, for 100%, 70%, then 50% damage; no retaliation.'),
  dread: ability('Dread', 'Adjacent enemies lose 10 morale at each round start.'),
  hearth: ability('Hearth', 'Adjacent allies gain Bloom 1 at each round start.'),
  standard_bearer: ability('Standard Bearer', 'Adjacent allies ignore the mixed-faction morale penalty.'),
  quench: ability('Quench', 'Adjacent companies on both sides cannot gain Burn.'),
  cornered: ability('Cornered', 'Gains +1 Attack for each 20% of its starting count lost.'),
  first_blood: ability('First Blood', 'Its first attack of the battle deals double damage.'),
  last_stand: ability('Last Stand', 'While its only surviving non-summoned ally, it takes half damage and retaliates without limit.'),
  ambush: ability('Ambush', 'May deploy on any legal hex on its own half of the battlefield.'),
  burrow: ability('Burrow', 'Spend the action to leave the field, then return at the start of its next turn on a legal empty hex.', 'actor'),
  rear_guard: ability('Rear Guard', 'Cannot be melee-attacked while another allied company is adjacent to the attacker.'),
  wall_walker: ability('Wall Walker', 'Ignores wall hexes and siege walls for movement and does not block them.'),
  pathfinder: ability('Pathfinder', 'While carried, Deepwood, Mosswold, and The Hush terrain costs the hero 100 movement.'),
  beast_of_burden: ability('Beast of Burden', 'While carried, grants the hero +150 movement each day.'),
  ley_touched: ability('Ley-Touched', 'While carried, grants the hero +1 mana each day.'),
  tithe_bearer: ability('Tithe-Bearer', 'While carried, grants 50 gold each day.'),
  far_sighted: ability('Far-Sighted', 'While carried, grants +2 reveal radius.'),
  carrion_sense: ability('Carrion Sense', 'While carried, reveals guarded reward objects within 5 tiles.'),
  sea_legs: ability('Sea Legs', 'While carried, embarking and disembarking cost 150 movement instead of 300.'),
  mindless: ability('Mindless', 'Cannot receive morale extra actions and is immune to morale drains.'),
  feral: ability('Feral', 'If its turn begins without an adjacent ally, it attacks the nearest company of either side.'),
  hungry: ability('Hungry', 'Costs 100 gold per day while carried; if unpaid, leaves at week start.'),
  slow_witted: ability('Slow-Witted', 'Always acts last in the round regardless of Speed.'),
  brittle_bones: ability('Brittle Bones', 'Takes 25% more melee damage.'),
  unruly: ability('Unruly', 'Cannot be targeted by allied spells; enemy spells may target it normally.'),
};

export function validateAbilityPresentation(): void {
  for (const [id, entry] of Object.entries(ABILITY_PRESENTATION)) {
    if (!entry.name.trim() || !entry.description.trim()) {
      throw new Error(`Missing ability presentation: ${id}`);
    }
  }
}
