/** Authoritative in-world text from docs/23_FLAVOR_TEXT.md. */
const UNIT_FLAVOR: Record<string, string> = {
  Yeoman: 'He was at the harvest last month. He will be at the next one.',
  Longbowman: 'Six days a farmer, one day the reason the levy holds.',
  Bannerman: 'Where the cloth goes, the line goes. He has never once looked back to check.',
  'Lance Knight': 'Three generations of the same armor, resized.',
  'Oriflamme Warden': 'Keeper of the old banner. Nobody weaves like that now; possibly nobody ever did.',
  'Oriflamme Wyvern': "The beast from the kingdom's arms, walked off the cloth. It looks exactly like its embroidery, which is not how animals look.",
  'Tin Soldier': 'Cast from the holy molds, rank upon rank, as the Founders intended.',
  'Hobby Knight': "It rocks as it charges. The Guild calls this the Founders' gait and copies it faithfully.",
  Marionette: 'It moves like a duelist remembering strings. The Guild insists there are no strings.',
  'Stuffed Sentinel': 'A thousand blows and no complaint. The stitching is ritual.',
  'Wooden Colossus': 'Its joints are original. The Guild only winds it, and sings while winding.',
  'Reliquary Ark': 'The hoard itself, wheeled to war. The procession walks behind it, repairing as it goes.',
  'Candle-Wisps': 'Small lights that go out reaching for something. Briefly, everything nearby feels what they wanted.',
  Couriers: 'Still carrying the letter. When one falls, another remembers the address.',
  Sentries: 'The watch was never relieved, so the watch continues.',
  'Bone Choir': 'They sing the endings of songs. The more endings a battle has, the better they sing.',
  'The Brides': 'She came back for the wedding once already. She will come back once more.',
  'The Ferry': 'A funeral barge that mislaid its river. It crosses anyway, and will carry the living, gently, as practice.',
  'Larval Tide': "The Hive's smallest courtesy. There is always more of it.",
  'Paper-Wasp Lancers': 'They strike, apologize formally, and are elsewhere.',
  'Silk-Spinners': 'Their thread is a gift. Recipients rarely move to accept it.',
  'Amber-Carriers': 'Where they walk, the world becomes Hive. This is offered as an improvement.',
  'Dragonfly Cavalry': 'Two guests greeted in one pass. The Hive values efficiency in its hospitality.',
  'The Half-Woken Queen': 'She learned speech during the Falling and uses it beautifully. What she says, courteously, is that everything will be gathered in.',
  'Crow Chorus': 'They know your name and use it against you in the old grammar.',
  'Fence-Post Familiars': 'The fence marks where the wood begins. The wood begins wherever the fence is standing.',
  'Besom Riders': "Sweeping is women's work, the villages said. So the wood sends its women sweeping.",
  Rusalka: 'Her song is an invitation. The invitation is not declinable.',
  Leshy: 'Count your steps in his wood. He counts them too, differently.',
  'The Walking Hut': "The house does the Crone's visiting for her. It has excellent legs and no manners.",
  Outriders: 'Strike, laugh, gone. The steppe teaches exits.',
  'Drum-Callers': "The drums don't signal the charge. The drums are the charge.",
  'Ashmane Wolves': 'They smell which herds have already bled. The steppe wastes nothing; neither do they.',
  'Aurochs Herd': 'You do not fight a stampede. You are underneath it or you are elsewhere.',
  'Grass-Serpent': 'The grass moves against the wind. That is all most ever learn of it.',
  Thunderbird: 'The old sky burned. It carries some of that sky with it, and shares.',
  'Masked Duelist': 'Impeccable form, borrowed face. Applaud and it bows.',
  'Hearth-Hound': 'The mastiff from every tavern sign, sign-sized.',
  'Wax Servitor': 'Candle-tenders made of candle. They melt a little in service and consider it tithe.',
  'Seam Moth': 'Its left wing remembers one moon. Its right remembers another. They meet only while it flies.',
  'Chalk Wight': 'It walks the boundary with one white finger, correcting the world where the line has smudged.',
  'Ember Toad': 'A coal learned patience, damp feet, and one very persuasive croak.',
  'Glass Hound': 'The Court gave it a different face for every hunt. It has kept the teeth from all of them.',
  'The Tallyman': 'He records every ending before the masks come off. His totals are never challenged twice.',
  'Lantern Bearer': 'He tends a light lit one moment before the bells stopped. It has been punctual ever since.',
  'Bone Orchard': 'Each white bough was planted separately. Together they have learned to draw a bow.',
  'Stitch-Ox': 'The yoke crosses three old borders. The ox regards all of them as one furrow.',
  'The Nine-Mouthed Well': 'Nine mouths ask for water. The well walks until somebody answers.',
  'Kiln Drake': 'Potters follow at a respectful distance. Its shed scales make excellent roof tile.',
  'Whistling Nan': 'She knows the tune that makes a hedge remember every trespass. The second verse costs extra.',
  'The Unbaptized': 'The water was late. It stood up anyway, owing no name and listening to no blessing.',
  Bellfounder: 'He has never cast a bell. He knows precisely when every hammer ought to fall.',
  'The Sleeper': 'A hill that breathes. Whatever is done to it by evening is undone by morning.',
  'The Mirror-Bound': 'Masked figures around a standing glass. Blades return to their wielders. The mirror does not care for arrows.',
  'Wall Section': 'Freshly made and firmly meant.',
  Ram: 'Oak, iron, and a single blunt opinion.',
  Watchtower: 'Someone is always looking outward.',
  'Standing Mirror': 'The glass is listening, and repeats what it hears.',
  "Maker's Wall": 'Argument, in stone, delivered instantly.',
  Sirens: 'Every sailor hears a different name. It is always the right one.',
  'Drowned Crew': 'They maintain the wreck. They are behind schedule and aware of it.',
  'Hull-Turtle': 'Barnacled, patient, occasionally mistaken for an island.',
  'Lantern-Angler': 'A light in the dark water, exactly where you hoped one would be.',
};

const SPELL_FLAVOR: Record<string, string> = {
  Rally: 'Remember what the banner says. All of it.', Blessing: 'A steadied hand strikes truest.',
  'Standard of Dawn': 'Raise it, and every small victory rings like a bell.', Amplify: 'Say it again, louder, and mean it.',
  Sanctuary: 'What is consecrated cannot be touched by clever words.', 'Oath of Iron': 'Sworn to stand; the blows agree to be smaller.',
  Consecrate: 'Clean cloth, clean wounds, clean start.', 'Hymn of the Host': 'The verses grow with the deeds.',
  Beacon: 'All roads home are short roads.', Trial: 'The proud multitude is called to account.',
  Census: 'Ask properly, and every banner answers.', 'Feast Day': 'Declare it, and the tables fill themselves.',
  Clarion: 'One note, and hearts arrive at their conclusion early.', 'Vigil of the Host': 'The weariest watch is watched over.',
  Oathbind: 'Bound to be only what it is.', 'Wayside Shrine': "Hallow the ground you'll bleed on.",
  'Forge-Spark': 'A little of the forge, delivered.', Ward: 'The blow was fine work; the counter-work was finer.',
  Reflect: 'What was made once is easily made twice.', Forgefire: 'The heat learns to keep itself.',
  'Clockwork Escort': 'Soldiers on short notice, no complaints, some ticking.', 'Wall of the Maker': 'Argument, in stone, delivered instantly.',
  Quicksilver: 'Oiled joints and lightened boots.', Gate: 'Two doors, one doorway.',
  Unmake: 'Every made thing has a seam. Find it.', Ironclad: 'For the properly armored, the day is quieter.',
  'Salt the Vein': 'The mine will spend a while remembering how.', 'False Colors': 'Wear the shape of something dull and local.',
  'Clockwork Courier': 'Distance is a paperwork problem.', Brittle: 'Its cleverness develops a crack.',
  'Standing Mirror': 'The glass repeats every word said against you, verbatim, at volume.', 'Summon Skiff': 'A boat, punctual, unexplained.',
  Wither: 'Everything ends; this merely schedules it.', 'Grave-Chill': "The cold that isn't weather.",
  "Mourner's Veil": 'Grief keeps its own; harm passes politely by.', Dirge: 'Each ending taught the song a verse.',
  'Last Candle': 'Every loss lights something.', Sour: 'Blessings keep poorly.',
  'Cold Road': 'Walk between the places where walking stopped.', Remembrance: 'Named rightly, some of them find their way back.',
  Reckoning: 'Spend everything. Everyone pays.', Quiet: 'It has been asked, firmly, to let things happen.',
  'Borrowed Time': 'Tomorrow, lent to today, at interest.', 'Pale Procession': 'Where enough fell, some will rise to walk a while.',
  'Silence the Passing': 'The dead may not speak their last word.', 'The Toll': 'Every ending pays the ferryman; be the ferryman.',
  "Death's Ledger": 'The graves keep excellent records.', 'Grave-Speech': 'Ground remembers. Ask it to repeat itself.',
  Gale: 'The sky takes a side.', Bloom: 'Told to grow, it grows.', Overgrow: 'Nothing in a garden stays where it was planted.',
  Thicket: 'The ground develops opinions.', Rains: 'What burns, soothed; what grows, encouraged.',
  'Beast Tongue': 'Their price is speakable, if you speak it.', 'Stampede Call': 'One word, and the herds answer at herd speed.',
  Storm: "The tall and the flying are introduced to the sky's temper.", Greenway: 'The forest is one place, if you know the door.',
  'Wild Growth': 'A good word in the right soil.', Murmuration: 'A thousand small eyes, briefly yours.',
  'Green Tide': 'The wood carries its friends.', 'Root and Ruin': 'Here, the map is wrong now.',
  'Fickle Weather': 'The week reconsiders.', 'Hourglass Crack': 'Time, mended badly on purpose.',
  'Borrow Shape': 'The mask fits anything.', Echo: 'The seam repeats what it heard.',
  'Loyal Unto Death': 'And one moment past it.',
  Kindle: 'The smallest faithful flame still knows its office.',
  Sunlance: 'Dawn keeps one bright spear for the faithless.',
  'Steady Hands': 'The vow is spoken first by the fingers.',
  Wellspring: 'A cup raised here fills a cup beyond the hill.',
  'Second Wind': 'The bell calls the fallen portion home.',
  'Litany of Dawn': 'Every throat finds the same first note.',
  'Hold the Line': 'The last foot of ground remembers its oath.',
  'Consecrated Ground': 'The field listens, and learns the older words.',
  Reprise: 'Once more, before the echo has finished.',
  Rivet: 'Fastened well, even anger holds its shape.',
  Whetstone: 'The edge recalls what work was promised.',
  Shrapnel: 'The first answer breaks into several smaller arguments.',
  'Ammunition Cart': 'Every empty quiver hears wheels approaching.',
  Detonate: 'The forge waits patiently inside every ember.',
  'Clockwork Double': 'The pattern turns once and finds a twin.',
  Blink: 'Here and there differ by a single good hinge.',
  Overclock: 'The spring objects later, never now.',
  'Dimension Door': 'The map folds politely around one impossible step.',
  'Pinch of Ash': 'A little ending, carried carefully between two fingers.',
  Tithe: 'The grave accepts small payments and keeps exact change.',
  Grudge: 'A knot remembers every hand that tightened it.',
  Yoke: 'What burdens one shoulder may burden another.',
  'Grave Bargain': 'The account closes on one name and opens beneath all the others.',
  'Puppet Strings': 'The dead learned obedience; the living merely borrow the lesson.',
  Nettle: 'The smallest leaf knows where the skin is thinnest.',
  Bramblelash: 'The hedge reaches farther when angered.',
  Wildcall: 'Something in the wood has heard its older name.',
  'Sap and Sinew': 'Green strength remembers that bone was once a branch.',
  'Verdant Surge': 'The whole field takes one deep green breath.',
  'The Turning Year': 'Every season arrives; only one is permitted to remain.',
  Fly: 'The road looks very reasonable from above.',
  Scrying: 'The lens does not see farther; it persuades distance to stand nearer.',
  'Bell, Book, and Candle': 'Three witnesses, and every second deed pays its tithe.',
  'Procession of Lamps': 'A road is only a promise repeated often enough.',
  Dayspring: 'Morning enters every wound at once.',
  'The Long Oath': 'The vow outlives the breath that first made it.',
  Prospect: 'Stone is shy about its wealth, never silent.',
  Counterweight: 'The world may pull. The plumb has already answered.',
  Bulwark: 'A city wall, folded small enough for a marching case.',
  'The Unmaking Engine': 'It has no reverse gear because reversal is its only motion.',
  'Mirror Hall': 'Every true word acquires a second destination.',
  'Second Grave': 'The first earth was merely a rehearsal.',
  'Ashen Pall': 'The ash falls evenly, but not kindly.',
  'The Ledger Balanced': 'One loss entered here becomes another loss there.',
  Ossuary: 'Every shelf is a barracks awaiting the proper bell.',
  'Steal Away': 'Ore follows the quieter cart.',
  'The Long Silence': 'Even magic lowers its voice around the final account.',
  Harvest: 'What the sickle takes, the grave distributes.',
  'The Debt Called': 'The road closes when the old account opens.',
  'Beast Sense': 'The wood has tracks where other eyes find only leaves.',
  'Ill Wind': 'It arrives before the army and waits in their lungs.',
  'Root the Sky': 'Every wing remembers the ground eventually.',
  'Beast Sovereign': 'No throne, only antlers and the agreement of teeth.',
  'Wind Shear': 'The centre holds; everything else is negotiable.',
  'The Long Green': 'Spring has learned the patience of conquest.',
  'The Weather Itself': 'The sky deals openly and never apologizes.',
};

const SKILL_FLAVOR: Record<string, string> = {
  Logistics: 'Roads respect a planner.', Scouting: "Count before you're counted.",
  Wayfaring: "Every terrain is a road if you've walked enough of them.", Diplomacy: 'Most fights are a price negotiation, poorly opened.',
  Attunement: "The world hums; you've learned to hum along.", Command: 'They watch you to learn how afraid to be.',
  Forager: 'The land sets a table for those who look.', Spellthief: 'Their best words, overheard and kept.',
  Alchemist: 'Quicker hands than the bottle expects.', Chronicler: 'Those who write the story see more of its branches.',
  Palimpsest: 'Scrape the page; write a better word.', Twicetold: 'The twisting words come easiest to you.',
  'Curse-Eater': "What's thrown at you is nourishment, properly chewed.", Ritualist: 'The calendar is a door, and you have keys.',
  Peddler: 'Buy grief, sell it as experience.', Warden: "Your walls fight like you're standing on them.",
  Ransomer: 'Defeat, invoiced.', Beastmaster: 'The herds have decided about you, favorably.',
  Vanguard: 'The first moment belongs to the prepared.', Provisioner: 'Deep pockets, deeper habits.',
  Siegewright: 'Walls are a puzzle with one answer.',
  Evoker: 'The smallest spark has always wanted a larger stage.',
  Tallykeeper: 'Every mark is entered twice, once in ink and once in consequence.',
  Reliquarian: 'Old objects speak most clearly to careful hands.',
  Tactician: 'The field is decided before the first boot touches it.',
  Reaper: 'Nothing useful is left sleeping beneath the churned earth.',
  Quartermaster: 'Every distant cupboard has a key, and every key has a label.',
  Beguiler: 'A kind word arrives first; the command hides inside it.',
  Loremaster: 'The margin remembers what the page forgot.',
  Duelist: 'One bright challenge, and the crowd finds its breath again.',
};

const ITEM_FLAVOR: Record<string, string> = {
  'Potion of Vigor': 'Courage, bottled, slightly fizzy.', 'Draught of Iron': 'Tastes like licking an anvil. Works accordingly.',
  'Smelling Salts': 'Every affliction agrees to leave the room.', "Hare's Heel": 'Fast feet, borrowed briefly.',
  'Blackfire Oil': 'For blades that want opinions.', 'Grave Dust': 'Do not inhale. Do throw.',
  'Hornet Jar': 'Open toward the enemy. This is the entire instruction.', 'Milk of the Moon': 'Drink this and forget your tricks. Best served to others.',
  'Chalk of Walls': 'Draw the wall. The wall takes it from there.', 'Wax Seal': 'This blessing is not to be tampered with, by order.',
  'Powder of Unmaking': 'For arguments written in the air.', 'Banner Whistle': 'One note; every heart in earshot stands taller.',
  'Second Candle': 'Relit, some of them.', 'Bottled Echo': "The battle's last word, repeatable.",
  Waybread: 'Miles, baked in.', 'Salted Meat': 'Morale and miles, sent by courier.',
  "Cartographer's Case": 'Someone already drew this. Unroll.', 'Tavern Tales': 'Third-hand, but the third hand was reliable.',
  Hearthstone: 'Home, the short way.', "Ferryman's Coin": "Fare for one crossing that shouldn't be possible.",
  'Militia Writ': 'The law can march surprisingly fast.', "Beggar's Coin": 'Luck owes the poor. Collect.',
  "Founders' Tin": 'A full rank of little soldiers, loyal to whoever opens the lid.', "Crone's Bundle": "Knotted thrice. She knows what's in it. You will find out.",
  "Overseer's Charter": 'Signed, sealed, and interested in every cartload.', 'Trade Goods': 'Useful elsewhere, which is their chief quality.',
  'Spell Scroll': 'A patient word waits under the ribbon.',
  'Spell Tome': 'A whole word waits behind one heavy clasp.',
  'Vial of Borrowed Hours': 'Tomorrow will notice the shortage eventually.',
  'Wildfire Flask': 'The cork is the only cautious part.',
  'Counterfeit Coin': 'Legal tender in any argument that has already happened.',
  'Grave-Dust Sachet': 'The dust remembers no uniform, only the hand that scattered it.',
  'Tuning Fork': 'Strike once. The chosen grammar rings true thereafter.',
  'Sealing Wax Cord': 'A knot, a seal, and a very firm refusal.',
  'Iron Filings': 'Every mark finds the same hot little magnet.',
  'Loose Thread': 'Pull here, and elsewhere comes loose.',
  'Ledger Page': 'The dead are entered in triplicate.',
  'Nightjar Feather': 'Even alarm bells lose the bird among the dusk.',
  "Surveyor's Twine": 'Eight miles of certainty, wound on a patient reel.',
  'Spellbook Page': 'It remembers which chapters it may belong to.',
};

export const TERRAIN_PRESENTATION = {
  meadow: { label: 'Grass', phrase: 'Grass.' }, deepwood: { label: 'Deepwood', phrase: 'Old trees, older shade.' },
  mosswold: { label: 'Mosswold', phrase: 'The moss grows in a pattern. The pattern repeats.' },
  ashsteppe: { label: 'Ashsteppe', phrase: 'The grass grew back. The ash stayed underneath.' },
  barrowfield: { label: 'Barrowfield', phrase: 'Quiet country. Well-tended.' },
  lacquerFlats: { label: 'Lacquer Flats', phrase: 'Smooth stone, strange grain, and a shine no rain explains.' },
  hush: { label: 'The Hush', phrase: 'Snow that fell somewhere else, on somewhere else, and settled here.' },
  mire: { label: 'Mire', phrase: 'The ground is negotiable.' },
  mountain: { label: 'Mountain', phrase: 'No road goes over.' }, water: { label: 'Water', phrase: 'Deep enough.' },
  seam: { label: 'Seam', phrase: 'The land changes its mind.' },
  road: { label: 'Road', phrase: 'Someone walked here first.' },
} as const;

export const BATTLE_TILE_PRESENTATION = {
  resin: { label: 'Resin', phrase: 'Sweet, gold, and gripping.' },
  undergrowth: { label: 'Undergrowth', phrase: 'It grabs at ankles.' },
  wall: { label: 'Wall', phrase: 'Freshly made and firmly meant.' },
} as const;

export const unitFlavor = (name: string): string => UNIT_FLAVOR[name] ?? `${name} keeps its own old customs.`;
export const spellFlavor = (name: string): string => SPELL_FLAVOR[name] ?? 'The words remember what to do.';
export const skillFlavor = (name: string): string => SKILL_FLAVOR[name] ?? 'Practice has made the road familiar.';
export const itemFlavor = (name: string): string => name.startsWith('Scroll of ')
  ? `The word ${name.slice(10)} waits under the ribbon.` : ITEM_FLAVOR[name] ?? `${name} has passed through careful hands.`;

const ARTIFACT_FLAVOR: Record<string, string> = {
  "Skirmisher's Blade": 'Nicked, balanced, dependable.', 'Seven-League Boots': 'The cobbler exaggerated by four leagues at most.',
  'Crown of the Patterned Sky': 'The pattern is of no known sky.', "Falconer's Glove": 'The bird counts better than you do.',
  'The Quiet Horseshoe': 'Small trouble finds other roads.', "Tinker's Spectacles": 'See what the fight is worth before the fight.',
  'Purse of the Prudent Toad': 'It simply fills. Do not ask the toad.', "The Bee-Charmer's Veil": 'The clinging world lets you pass as kin.',
  'The Sundered Hourglass': 'Every other moment, there is more moment.', 'The Longest Candle': 'One light refuses the dark, once.',
  'The Crooked Distaff': 'Their luck arrives pre-spun, and badly.', 'Banner of the First Field': 'Hearts finish early under it.',
  'The Patchwork Standard': 'Every color of every fallen world, sewn together; strangers fight like family beneath it.',
  Seamstone: 'A piece of the boundary. The world nearby agrees to your terms.', 'Mirrorshard Pendant': 'The first curse sent to you is returned unopened.',
  "The Bell's Clapper": 'Stolen. The brothers want it back. Once a battle, everything holds its breath.', "Queen's Amber": 'The smallest lives multiply in its light.',
  "Wolf-Mother's Torc": 'Her children bite twice.', 'Horn of the Broad World': 'For one breath, everything is the size it was back home.',
  "The Toy Knight's Heart": 'Sewn in, wound up, briefly unwilling to stay broken.', 'The Needle': 'A needle. It has no business being this heavy.',
  'The Golden Thread': 'It does not tangle, end, or explain itself.', 'The Thimble': 'Worn by whom? Sized for what finger?',
  'The Patternbook': 'Diagrams of garments no body could wear. Some pages show landscapes.',
  'Knucklebones of the Saint': 'They land well. They always land well.', 'Drum of the Deep Grass': 'A heartbeat for the whole line.',
  'Censer of Stillness': 'Their first clever word comes out expensive.', 'Pocket Sundial': 'It runs a little ahead, and so may you.',
  'Iron Nail': 'Cold iron refuses the first trick. Once.', 'The Mirror Mask': 'Strike it and be struck; the mask keeps perfect accounts.',
  'The Bellows': 'The coals remember every breath.', 'The Nine-Pip Cord': 'It counts faster when the pattern catches.',
  'Ash Censer': 'A little ash goes looking for the rest.', "Sapper's Chalk": 'Every line it draws expects to become a wall.',
  'Loom of Small Repairs': 'Nothing whole was ever beyond a patient shuttle.', "Puppeteer's Thimble": 'The strings linger after the hand lets go.',
  'The Quiet Ledger': 'One name may be entered. The ink returns as power.', "Beast-Caller's Cord": 'The answering feet arrive already running.',
  'Empty Reliquary': 'It keeps exactly what is entrusted, and nothing else.', 'The Cracked Prism': 'One ray enters. Two arguments leave.',
  'The Second Sunrise': 'Dawn has been carefully saved for later.', "Hexwright's Tally": 'Nine was a custom, not a law.',
  'The Grafted Hand': 'It remembers a second gesture before the first is done.', 'Discordant Fork': 'The field hums for one listener only.',
  'The Whistling Kettle': 'It chooses whose trouble comes to the boil.', 'The Tuning Peg': 'The third string was always there, if pulled tight enough.',
  'The Greedy Grimoire': 'It leaves no hand free for smaller remedies.', 'The Loud Bell': 'Everyone hears where it has gone.',
  'The Iron Tongue': 'Cheaper words, once silence has had its due.', 'The Split Reed': 'Every note is perfected. The breath is not.',
};
export const artifactFlavor = (name: string): string => ARTIFACT_FLAVOR[name] ?? `${name} bears the marks of long keeping.`;

export const BUILDING_FLAVOR: Record<string, string> = {
  'Village Hall': 'Where the taxes start.', 'Town Hall': 'Where the taxes improve. Requires nothing but ambition.',
  'City Hall': 'Marble now. The taxes have arrived.', Marketplace: "Everything has a price here, and it isn't a fair one.",
  Tavern: 'Heroes between stories, for hire. Also soup.', 'Mage Guild': 'The ink is expensive because the words argue back.',
  Walls: 'Politeness in stone.', Keep: 'Impoliteness in stone.',
  'Chapel of the Banner': 'The relic cloth hangs here. Soldiers stand straighter under it than the sermon requires.',
  'Muster Field': 'Room to drill everyone the parishes send, and the parishes send more when there is room.',
  'Guild Workshop': "Broken is not dead. The Guild's whole theology, with workbenches.",
  "Founder's Vault": 'The deepest reliquaries. Sometimes the Founders provide; the Guild does not ask how.',
  'Chapel of Candles': 'Every candle here is somebody. The fallen find their way back to the flame, eventually, in part.',
  Lychgate: 'The proper door for the dead. Defended properly, everything here dies twice as meaningfully.',
  Rendery: "The Hive's larder and nursery, which are one room.", 'Deep Tunnels': 'The Hive does not recognize your surface distances.',
  'Bargain Post': 'A crossroads desk where the wood does business. Read everything.',
  'The Hen-Legged Fence': 'The town would simply rather be somewhere else, some weeks.',
  'Great Kraal': 'The herds calve better within earshot of the drums.',
  'Pyre of the Fallen': 'The clans burn their dead loudly. The dead appreciate it, audibly.',
  Shipyard: 'Keels laid to old patterns. Some of the patterns insist on figureheads.',
};
export const buildingFlavor = (name: string): string => BUILDING_FLAVOR[name]
  ?? (name.includes('Dwelling') ? 'They muster here weekly, per the old arrangement.' : `${name} keeps the town in working order.`);

export const MAP_OBJECT_FLAVOR: Record<string, string> = {
  mineGold: 'The vein runs deep and the ledger runs deeper.',
  mineTimber: 'Sawdust, rope, and honest noise.',
  mineIron: 'The hills give up their bones slowly.',
  mineEssence: 'Something rises here that no bucket holds properly.',
  pile: 'Someone dropped this. Or left it. Or fled.',
  chest: 'Locked, which is a kind of promise.',
  waystation: 'Fresh horses, strong tea, no questions.',
  shrineRite: 'You could steady your heart here, and your banner-hand.',
  shrineCraft: 'The forge is cold but the anvil remembers.',
  shrineGrave: 'Leave a candle. Take something quieter.',
  shrineWild: 'The grove listens. Speak carefully.',
  barrowField: 'The dead here were buried with their letters unsent.',
  seam: 'Two lands meet here that never used to be neighbors. They are civil about it.',
  tinkersCart: "Pots, pans, and one thing you didn't know you needed. He'll be gone by Thursday.",
  monastery: 'The brothers keep the hours of a clock no one built. The great bell has never rung. Pray it stays polite.',
  gloamingRing: 'Leave a gift in the circle and come back in a week. It is rude to watch.',
  storyteller: "Sit. Everyone's road passes this fire eventually, and every road makes a story.",
  chrysalis: 'The water is warm and does not reflect you correctly. Bathers come out... promoted.',
  bridge: 'Perfect stonework, stopped mid-span, as if the masons were called away between one stone and the next. It could be finished.',
  hedgeSchool: 'A teacher, a bench, and lessons no academy would print.',
  reliquaryCairn: 'Give the stones something precious and the stones will trade. They have odd taste.',
  stacks: 'Three shelves lean close. Only one book means to leave.',
  wildShrine: 'The roots keep no catalogue, and offer no apology.',
  reliquaryOfPages: 'One guarded page waits behind a dozen empty clasps.',
  tollGate: "The Keeper's rates are posted. The Keeper's mace is also posted.",
  omenStone: 'Weather, harvests, and worse: it is all written here a week early, for those who can read stone.',
  richVein: 'Essence bleeds from a crack in the world. It will not bleed forever.',
  dwelling: 'They live here, after their fashion. Some would travel, for pay or purpose.',
  lockSleeper: 'A hill that breathes. Whatever is done to it by evening is undone by morning.',
  lockMirror: 'Masked figures around a standing glass. Blades return to their wielders. The mirror does not care for arrows.',
  crone: 'A kettle sings at a crossroads where no house stands.',
  item: 'Something useful waits where it was left.',
  boat: 'A borrowed road with a keel under it.',
  manaSpring: 'The water remembers being sky. Drink standing up.',
  flotsam: "Someone's cargo. The sea has amended the bill of lading.",
  sealedCask: 'Tarred, corked, and heavier than hope.',
  castaway: 'He has been extremely alone and would like to discuss it.',
  messageBottle: 'The handwriting is urgent. The date is unhelpful.',
  whirlpool: 'The two seas argue here. Travelers are the concession.',
  shipwreck: 'The figurehead is still smiling. Nothing else is.',
  drownedBell: 'Below, at anchor, a bell. It has rung exactly once, downward.',
  sirenRocks: 'The song is about you, specifically. It is very flattering.',
  lighthouse: 'Somebody keeps it lit. Nobody rows out to ask who.',
  watermill: 'The wheel turns for whoever oils it.',
  windmill: 'It grinds what the week brings.',
  tradingCamp: 'Everything is for sale here, including directions.',
  sparringStone: 'Generations have hit this rock. The rock has learned nothing. The visitors have.',
  listeningStones: 'Stand in the circle. The circle finishes your sentences.',
  longDraught: 'A well with opinions about you.',
  grinningIdol: 'It grins. Eventually you get the joke; the joke is favorable.',
  hutOnTheHill: "There's a hut here most days. The path to the door negotiates.",
  treeSecondThoughts: 'It grew through a library, once. It remembers enough to charge.',
  warmTable: 'Soup, bread, and the strong impression of being expected.',
  coldSpring: 'Water with somewhere to be.', idolOfSomebody: 'Nobody remembers whom. It accepts flowers on their behalf.',
  wishingWell: 'Rates of return vary. The splash is guaranteed.',
  ruinedWatchtower: 'The garrison left in a hurry, in several directions, some time ago.',
  oldBearsCave: 'Occupied. Firmly.', wolfHollow: 'The howling is administrative: territory, hours, grievances.',
  unquietYard: "The residents keep it tidy and dislike the phrase 'final resting place.'",
  moltingCourt: 'Something grew up here and grew out of here. The husks stand in receiving lines.',
  spoolHoard: 'Wound around the great cylinder: thread, wire, and things that glint.',
  mercenaryCamp: 'Loyalty by the week, invoiced in advance.',
  wagonCamp: 'Everything fell off a cart. Technically theirs, now technically yours.',
  titheBarn: 'The granary tithes back, at interest, to the pious and the liquid.',
  skeletonGrass: 'He was carrying something. He is not attached to it, anymore, in any sense.',
  coldCampfire: 'Whoever sat here left warm coals and cold trail.',
  shepherdsLeanTo: 'Wool, weather, and one forgotten useful thing.',
  overgrownCart: "The oxen made it. The cargo didn't.",
  patientStone: "The stone shows a picture, patiently, in pieces. It has all the time you don't.",
  cache: 'The sketch insists there is something under this exact patch of ground.',
  obstacle: 'The road has made other arrangements.',
};
