import type { SpellId, SpellSchool } from '../../core/types';
import type { EffectOperation, SpellDefinition } from './index';
import { spellFlavor } from '../flavor';

const spell = (
  id: SpellId, name: string, school: SpellSchool, mana: number | 'X',
  kind: SpellDefinition['kind'], base: string, plus: string,
  target: SpellDefinition['aiHints']['target'] = 'strongestEnemy',
  castWhen: SpellDefinition['aiHints']['castWhen'] = 'always',
  effectOperation?: EffectOperation,
  rarity: SpellDefinition['rarity'] = 'uncommon',
): SpellDefinition => ({
  id, name, flavor: spellFlavor(name), school, mana, kind, base, plus, rarity, effectOperation,
  aiHints: { target, castWhen },
});

/** Completion catalog from docs 15; topology and adventure entries are dealt normally. */
export const EXPANSION_SPELLS: SpellDefinition[] = [
  spell('beacon', 'Beacon', 'rite', 5, 'topology',
    'Travel to the nearest friendly town.', 'Choose any friendly town.', 'self', 'always', undefined, 'rare'),
  spell('census', 'Census', 'rite', 4, 'adventure',
    'Inspect every enemy hero for one day.', 'Lasts two days and shows movement.', 'self'),
  spell('feastDay', 'Feast Day', 'rite', 6, 'adventure',
    'All towns gain 25% growth this week.', 'Also gain 500 gold per town.', 'self'),
  spell('clarion', 'Clarion', 'rite', 4, 'staple',
    'Set an ally meter to 80.', 'Set it to 100.', 'strongestAlly'),
  spell('vigilOfTheHost', 'Vigil of the Host', 'rite', 5, 'enchantment',
    'Lowest-meter ally gains 15 each round.', 'Two lowest allies gain 15.', 'enchantmentSlot', 'round1'),
  spell('oathbind', 'Oathbind', 'rite', 5, 'build-around',
    'Enemy receives no effects for 2 rounds.', '3 rounds and loses abilities.', 'strongestEnemy', 'always', undefined, 'rare'),
  spell('waysideShrine', 'Wayside Shrine', 'rite', 5, 'adventure',
    'Next battle here has Rite resonance.', 'Choose the resonance school.', 'self', 'always', undefined, 'rare'),

  spell('gate', 'Gate', 'craft', 5, 'topology',
    'Open a paired passage between two explored points.', 'Passage lasts all week.', 'self', 'always', undefined, 'rare'),
  spell('saltTheVein', 'Salt the Vein', 'craft', 4, 'adventure',
    'Visible enemy mine yields nothing for 5 days.', 'Eight days; reveal its lost production.', 'self'),
  spell('falseColors', 'False Colors', 'craft', 4, 'adventure',
    'Appear as a neutral guardian band.', 'Choose the displayed band.', 'self'),
  spell('clockworkCourier', 'Clockwork Courier', 'craft', 4, 'adventure',
    'Transfer items or one stack between heroes.', 'Also transfer to or from garrisons.', 'self'),
  spell('brittle', 'Brittle', 'craft', 4, 'staple',
    'Disable enemy abilities for 2 rounds.', 'Three rounds and Burn 2.'),
  spell('standingMirror', 'Standing Mirror', 'craft', 7, 'build-around',
    'Enemy spells are copied at your Spell Power.', 'Choose new targets for the copies.', 'self', 'round1', undefined, 'rare'),
  spell('summonSkiff', 'Summon Skiff', 'craft', 7, 'topology',
    'Summon a boat to the nearest shore.', 'Steal the nearest enemy boat.', 'self', 'always', undefined, 'rare'),

  spell('coldRoad', 'Cold Road', 'grave', 5, 'topology',
    'Travel between explored barrows.', 'Carry an adjacent allied hero too.', 'self', 'always', undefined, 'rare'),
  spell('borrowedTime', 'Borrowed Time', 'grave', 4, 'adventure',
    'Double movement today; zero tomorrow.', 'Half movement tomorrow instead.', 'self'),
  spell('paleProcession', 'Pale Procession', 'grave', 5, 'adventure',
    'Raise temporary Candle-Wisps where 100 died.', 'Larger company serving seven days.', 'self'),
  spell('silenceThePassing', 'Silence the Passing', 'grave', 4, 'staple',
    'Enemy death triggers do not fire for 3 rounds.', 'Your death triggers fire twice.', 'self'),
  spell('theToll', 'The Toll', 'grave', 5, 'scaling',
    'Gain 2 mana per destroyed stack.', 'Gain 3 per destroyed stack.', 'self'),
  spell('deathsLedger', "Death's Ledger", 'grave', 6, 'adventure',
    'Reveal every barrow and its scroll.', 'Also reveal all guardian counts for one day.', 'self', 'always', undefined, 'rare'),
  spell('graveSpeech', 'Grave-Speech', 'grave', 5, 'adventure',
    'Replay a battle fought on this tile.', 'Learn one spell cast in it.', 'self', 'always', undefined, 'rare'),

  spell('gale', 'Gale', 'wild', 3, 'staple',
    'Push an enemy 2 hexes; collision deals 3% HP.', 'Push 3; collision 6% and Chill 1.',
    'strongestEnemy', 'always', undefined, 'common'),
  spell('bloom', 'Bloom', 'wild', 3, 'staple',
    'Bloom 3 on an ally.', 'Bloom 4; adjacent allies Bloom 1.', 'strongestAlly', 'always', undefined, 'common'),
  spell('overgrow', 'Overgrow', 'wild', 4, 'twister',
    'Spread an effect to adjacent stacks.', 'Exclude one adjacent stack.', 'counterPile', 'always', 'overgrow', 'common'),
  spell('thicket', 'Thicket', 'wild', 4, 'staple',
    'Create three slowing undergrowth hexes.', 'Enemies ending there gain Chill 1.', 'self', 'always', undefined, 'common'),
  spell('rains', 'Rains', 'wild', 3, 'staple',
    'Remove all Burn; allies gain Bloom 1.', 'Enemies also gain Chill 1.', 'self', 'always', undefined, 'common'),
  spell('beastTongue', 'Beast Tongue', 'wild', 5, 'adventure',
    'Pay beast guardians to disperse.', 'Or pay to recruit them.', 'self'),
  spell('stampedeCall', 'Stampede Call', 'wild', 6, 'build-around',
    'All allied beasts move toward enemies.', 'They also gain +2 speed this round.', 'self'),
  spell('storm', 'Storm', 'wild', 6, 'build-around',
    'All stacks lose 6% HP; flyers lose 12%.', 'Flyers lose 18%.', 'self'),
  spell('greenway', 'Greenway', 'wild', 5, 'topology',
    'Travel through forest up to 15 tiles.', 'Range 25 tiles.', 'self'),
  spell('wildGrowth', 'Wild Growth', 'wild', 5, 'adventure',
    'Owned dwelling gains 50% growth this week.', 'Gain 75%.', 'self'),
  spell('murmuration', 'Murmuration', 'wild', 3, 'adventure',
    'Draw a scouting path for a crow.', 'The crow also reveals nearby objects.', 'self', 'always', undefined, 'common'),
  spell('greenTide', 'Green Tide', 'wild', 5, 'adventure',
    'Forest costs no movement this week.', 'Also reveals connected forest.', 'self'),
  spell('rootAndRuin', 'Root and Ruin', 'wild', 5, 'adventure',
    'Grow a three-tile map thicket for 3 days.', 'Five tiles for 5 days.', 'self'),
  spell('fickleWeather', 'Fickle Weather', 'wild', 6, 'adventure',
    'Replace the omen with one of two offers.', 'Choose from three.', 'self', 'always', undefined, 'rare'),
  spell('shedSkin', 'Shed Skin', 'wild', 4, 'staple',
    'Remove one active effect; gain equal Bloom.', 'May target an enemy and spread Bloom nearby.', 'weakestAlly'),
  spell('hedgerowMarch', 'Hedgerow March', 'wild', 5, 'enchantment',
    'Forced movement grants allies 10 meter.', 'It also grants Bloom 1.', 'enchantmentSlot', 'round1'),

  spell('hourglassCrack', 'Hourglass Crack', 'craft', 6, 'build-around',
    'Target acts twice this round and skips next.', 'Choose which future round it skips.', 'strongestAlly', 'always', undefined, 'rare'),
  spell('borrowShape', 'Borrow Shape', 'wild', 5, 'build-around',
    'Copy abilities from an adjacent enemy.', 'Copy from any visible enemy.', 'strongestAlly', 'always', undefined, 'rare'),
  spell('echo', 'Echo', 'rite', 4, 'build-around',
    'Recast the last spell at your Spell Power.', 'Resolve its + face.', 'self', 'always', undefined, 'rare'),
  spell('loyalUntoDeath', 'Loyal Unto Death', 'grave', 4, 'build-around',
    'Ally attacks its killer when destroyed.', 'No meter drain and restore 3 mana.', 'strongestAlly', 'always', undefined, 'rare'),
];
