import type { SpellId, SpellSchool } from '../../core/types';
import type { EffectOperation, SpellDefinition } from './index';
import { spellFlavor } from '../flavor';

const spell = (
  id: SpellId, name: string, school: SpellSchool, mana: number | 'X',
  kind: SpellDefinition['kind'], base: string, plus: string,
  target: SpellDefinition['aiHints']['target'] = 'strongestEnemy',
  castWhen: SpellDefinition['aiHints']['castWhen'] = 'always',
  effectOperation?: EffectOperation,
  rarity: SpellDefinition['rarity'] = 'uncommon',
): SpellDefinition => ({
  id, name, flavor: spellFlavor(name), school, mana, kind, base, plus, rarity, effectOperation,
  aiHints: { target, castWhen },
});

/** Completion catalog from docs 15; topology and adventure entries are dealt normally. */
export const EXPANSION_SPELLS: SpellDefinition[] = [
  spell('beacon', 'Beacon', 'rite', 5, 'topology',
    'Travel to the nearest friendly city.', 'Choose any friendly city as the destination instead of using the nearest one.', 'self', 'always', undefined, 'rare'),
  spell('census', 'Census', 'rite', 4, 'adventure',
    'Inspect every enemy hero for one day.', 'Inspect every enemy hero for two days instead of one and also reveal their movement.', 'self'),
  spell('feastDay', 'Feast Day', 'rite', 6, 'adventure',
    'All cities gain 25% growth this week.', 'All cities gain 25% growth this week, and each city also grants 500 gold.', 'self'),
  spell('clarion', 'Clarion', 'rite', 4, 'staple',
    'Set one ally’s morale to 80.', 'Set one ally’s morale to 100 instead of 80.', 'strongestAlly'),
  spell('vigilOfTheHost', 'Vigil of the Host', 'rite', 5, 'enchantment',
    'The lowest-morale ally gains 15 morale each round.', 'The two lowest-morale allies each gain 15 morale every round instead of only one ally.', 'enchantmentSlot', 'round1'),
  spell('oathbind', 'Oathbind', 'rite', 5, 'build-around',
    'One enemy receives no effects for 2 rounds.', 'One enemy receives no effects for 3 rounds instead of 2 and also loses its abilities.', 'strongestEnemy', 'always', undefined, 'rare'),
  spell('waysideShrine', 'Wayside Shrine', 'rite', 5, 'adventure',
    'The next battle here has Rite resonance.', 'Choose which school resonates in the next battle here instead of always using Rite.', 'self', 'always', undefined, 'rare'),

  spell('gate', 'Gate', 'craft', 5, 'topology',
    'Open a paired passage between two explored points.', 'Open the same paired passage, but keep it until the end of the week.', 'self', 'always', undefined, 'rare'),
  spell('saltTheVein', 'Salt the Vein', 'craft', 4, 'adventure',
    'One visible enemy mine yields nothing for 5 days.', 'One visible enemy mine yields nothing for 8 days instead of 5, and its lost production is revealed.', 'self'),
  spell('falseColors', 'False Colors', 'craft', 4, 'adventure',
    'Appear as a neutral guardian band.', 'Appear neutral and choose which guardian band observers see.', 'self'),
  spell('clockworkCourier', 'Clockwork Courier', 'craft', 4, 'adventure',
    'Transfer items or one company between heroes.', 'Transfer items or one company between heroes or to and from city garrisons.', 'self'),
  spell('brittle', 'Brittle', 'craft', 4, 'staple',
    'Disable one enemy’s abilities for 2 rounds.', 'Disable one enemy’s abilities for 3 rounds instead of 2 and give it Burn 2.'),
  spell('standingMirror', 'Standing Mirror', 'craft', 7, 'build-around',
    'Enemy spells are copied using your Spell Power.', 'Enemy spells are copied using your Spell Power, and you choose new legal targets for each copy.', 'self', 'round1', undefined, 'rare'),
  spell('summonSkiff', 'Summon Skiff', 'craft', 7, 'topology',
    'Summon a boat to the nearest shore.', 'Move the nearest enemy boat to the nearest shore for your use instead of creating a new boat.', 'self', 'always', undefined, 'rare'),

  spell('coldRoad', 'Cold Road', 'grave', 5, 'topology',
    'Travel between explored barrows.', 'Travel between explored barrows and carry one adjacent allied hero with you.', 'self', 'always', undefined, 'rare'),
  spell('borrowedTime', 'Borrowed Time', 'grave', 4, 'adventure',
    'Double movement today, then have zero movement tomorrow.', 'Double movement today, then retain half movement tomorrow instead of losing all of it.', 'self'),
  spell('paleProcession', 'Pale Procession', 'grave', 5, 'adventure',
    'Raise a temporary Candle-Wisp company where at least 100 creatures died.', 'Raise a larger Candle-Wisp company at that site, and keep it for seven days.', 'self'),
  spell('silenceThePassing', 'Silence the Passing', 'grave', 4, 'staple',
    'Enemy death triggers do not fire for 3 rounds.', 'Enemy death triggers remain suppressed for 3 rounds, while your own death triggers fire twice.', 'self'),
  spell('theToll', 'The Toll', 'grave', 5, 'scaling',
    'Gain 2 mana per destroyed company.', 'Gain 3 mana per destroyed company instead of 2.', 'self'),
  spell('deathsLedger', "Death's Ledger", 'grave', 6, 'adventure',
    'Reveal every barrow and its scroll.', 'Reveal every barrow and its scroll, and reveal all guardian counts for one day.', 'self', 'always', undefined, 'rare'),
  spell('graveSpeech', 'Grave-Speech', 'grave', 5, 'adventure',
    'Replay a battle fought on this tile.', 'Replay a battle fought on this tile and permanently learn one spell that was cast in it.', 'self', 'always', undefined, 'rare'),

  spell('gale', 'Gale', 'wild', 3, 'staple',
    'Push one enemy 2 hexes; a collision costs 3% HP.', 'Push one enemy 3 hexes instead of 2; a collision costs 6% HP instead of 3% and gives Chill 1.',
    'strongestEnemy', 'always', undefined, 'common'),
  spell('bloom', 'Bloom', 'wild', 3, 'staple',
    'Give one ally Bloom 3.', 'Give the target Bloom 4 instead of 3 and each adjacent ally Bloom 1.', 'strongestAlly', 'always', undefined, 'common'),
  spell('overgrow', 'Overgrow', 'wild', 4, 'twister',
    'Spread one active effect to every adjacent company.', 'Spread one active effect to adjacent companies, but choose one adjacent company to exclude.', 'counterPile', 'always', 'overgrow', 'common'),
  spell('thicket', 'Thicket', 'wild', 4, 'staple',
    'Create three slowing undergrowth hexes.', 'Create three slowing undergrowth hexes; enemies that end there also gain Chill 1.', 'self', 'always', undefined, 'common'),
  spell('rains', 'Rains', 'wild', 3, 'staple',
    'Remove all Burn, then give allies Bloom 1.', 'Remove all Burn, give allies Bloom 1, and give enemies Chill 1.', 'self', 'always', undefined, 'common'),
  spell('beastTongue', 'Beast Tongue', 'wild', 5, 'adventure',
    'Pay beast guardians to disperse.', 'Choose either to pay beast guardians to disperse or to recruit them.', 'self'),
  spell('stampedeCall', 'Stampede Call', 'wild', 6, 'build-around',
    'All allied beasts move toward enemies.', 'All allied beasts move toward enemies and gain +2 speed for this round.', 'self'),
  spell('storm', 'Storm', 'wild', 6, 'build-around',
    'All companies lose 6% HP; flyers lose 12% instead.', 'All companies lose 6% HP, but flyers lose 18% instead of 12%.', 'self'),
  spell('greenway', 'Greenway', 'wild', 5, 'topology',
    'Travel through connected forest up to 15 tiles.', 'Travel through connected forest up to 25 tiles instead of 15.', 'self'),
  spell('wildGrowth', 'Wild Growth', 'wild', 5, 'adventure',
    'One owned dwelling gains 50% growth this week.', 'One owned dwelling gains 75% growth this week instead of 50%.', 'self'),
  spell('murmuration', 'Murmuration', 'wild', 3, 'adventure',
    'Draw a scouting path for a crow.', 'Draw a scouting path for a crow, which also reveals nearby objects along the route.', 'self', 'always', undefined, 'common'),
  spell('greenTide', 'Green Tide', 'wild', 5, 'adventure',
    'Forest costs no movement this week.', 'Forest costs no movement this week, and connected forest is also revealed.', 'self'),
  spell('rootAndRuin', 'Root and Ruin', 'wild', 5, 'adventure',
    'Grow a three-tile map thicket for 3 days.', 'Grow a five-tile map thicket for 5 days instead of three tiles for 3 days.', 'self'),
  spell('fickleWeather', 'Fickle Weather', 'wild', 6, 'adventure',
    'Replace the omen by choosing one of two offers.', 'Replace the omen by choosing one of three offers instead of two.', 'self', 'always', undefined, 'rare'),
  spell('shedSkin', 'Shed Skin', 'wild', 4, 'staple',
    'Remove one active effect from an ally and give it equal Bloom.', 'Target an ally or enemy, remove one active effect, give equal Bloom, and spread Bloom nearby.', 'weakestAlly'),
  spell('hedgerowMarch', 'Hedgerow March', 'wild', 5, 'enchantment',
    'Forced movement grants allies 10 morale.', 'Forced movement grants allies 10 morale and Bloom 1.', 'enchantmentSlot', 'round1'),

  spell('hourglassCrack', 'Hourglass Crack', 'craft', 6, 'build-around',
    'One company acts twice this round and skips the next round.', 'One company acts twice this round, and you choose which of the next three rounds it skips.', 'strongestAlly', 'always', undefined, 'rare'),
  spell('borrowShape', 'Borrow Shape', 'wild', 5, 'build-around',
    'One ally copies abilities from an adjacent enemy.', 'One ally copies abilities from any visible enemy instead of requiring adjacency.', 'strongestAlly', 'always', undefined, 'rare'),
  spell('echo', 'Echo', 'rite', 4, 'build-around',
    'Recast the last spell using your Spell Power and its recorded version.', 'Recast the last spell using your Spell Power and force its Upgraded rules, even if the recorded cast was Standard.', 'self', 'always', undefined, 'rare'),
  spell('loyalUntoDeath', 'Loyal Unto Death', 'grave', 4, 'build-around',
    'One ally attacks its killer when destroyed.', 'One ally attacks its killer when destroyed, causes no allied morale drain, and restores 3 mana.', 'strongestAlly', 'always', undefined, 'rare'),
];
